# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Jonathan's Lab Notebook
author: Jonathan Pfeifer
logo: logo.png
exclude_patterns:
  [
    "/_*/**",
    "*/_*/**",
    "vscode-extensions/*",
    "_cache/*",
    "*readme.md",
    "*/experiment-template.ipynb",
    "_old/*",
  ]
# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: cache
  cache: _cache
  timeout: 60

  exclude_patterns: ["/_*/**", "**/_*/**", "**/vscode-extension**"]
# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

sphinx:
  config:
    # # for getting plotly to work
    html_js_files:
      - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    suppress_warnings: ["mystnb.unknown_mime_type"]
